'use client'
import {useState} from 'react'
import {CheckCircle2,Phone,Navigation,LockKeyhole} from 'lucide-react'
import {toast} from 'sonner'
import {useWorkspace,WorkspaceLoading} from '@/components/workspace-provider'
import {PageHeading,StatusBadge,Empty} from '@/components/market-ui'
import {FileUpload,FileLinks} from '@/components/file-upload'
import {ServiceMap} from '@/components/service-map'
import {ChatThread} from '@/components/chat-thread'
import {PaymentPanel} from '@/components/payment-panel'
import {paymentLabels} from '@/lib/payment-types'
import {formatFCFA} from '@/lib/data'
import type {FileRef} from '@/lib/marketplace'
export function DetailMissionClient({id}:{id:string}){
 const {state,act,busy}=useWorkspace();const [before,setBefore]=useState<FileRef[]>([]);const [after,setAfter]=useState<FileRef[]>([]);const [report,setReport]=useState('');const [showDispute,setShowDispute]=useState(false);const [reason,setReason]=useState('');const [evidence,setEvidence]=useState<FileRef[]>([]);const [decision,setDecision]=useState<'refund'|'release'>('refund');const [quality,setQuality]=useState(5);const [punctuality,setPunctuality]=useState(5);const [communication,setCommunication]=useState(5);const [comment,setComment]=useState('')
 if(!state)return <WorkspaceLoading/>
 const m=state.missions.find(m=>m.id===id);if(!m || (state.role==='professionnel'&&m.professionalId!==state.activeProId))return <div className="ap-page"><Empty text="Cette mission n’est pas accessible dans cet espace." href="/reservations" label="Voir mes missions"/></div>
 const p=state.pros.find(p=>p.id===m.professionalId)!
 const pro=state.role==='professionnel';const client=state.role==='client';const admin=state.role==='administrateur'
 async function transition(action:'accept'|'refuse'|'route'|'start'|'finish'|'validate'|'cancel'){const res=await act({type:'transition',missionId:id,action,before,after,report});if(res.ok)toast.success('Mission mise à jour.')}
 return <div className="ap-page"><PageHeading title={m.service} subtitle={`Mission ${m.id}`} back={pro?'/espace-pro':'/reservations'}/><div className="flex flex-wrap justify-between items-center gap-3 mb-6"><StatusBadge status={m.status}/><span className="text-sm inline-flex items-center gap-2 text-emerald-dark"><LockKeyhole size={16}/>{m.paymentFlow?(m.paymentFlow.mode==='mock'?'Simulation locale':'pawaPay sandbox'):'Paiement simulé historique'} : {paymentLabels[m.payment]}</span></div><div className="grid lg:grid-cols-[1.2fr_1fr] gap-6"><div className="space-y-5"><PaymentPanel mission={m}/><section className="ap-panel"><h2 className="font-bold text-lg">{p.name}</h2><p className="text-sm text-muted-foreground">{p.categorie} · {p.kyc==='verifie'?'Vérifié (démo)':'Vérification en cours'}</p><p className="mt-4 text-sm">{m.description}</p><dl className="space-y-2 mt-4 text-sm"><div className="flex justify-between gap-4"><dt>Adresse</dt><dd className="text-right">{m.address}, {m.quartier}</dd></div><div className="flex justify-between gap-4"><dt>Créneau</dt><dd>{new Date(m.date).toLocaleString('fr-FR',{timeZone:'Africa/Libreville',dateStyle:'short',timeStyle:'short'})}</dd></div><div className="flex justify-between"><dt>Prestation</dt><dd>{formatFCFA(m.basePrice)}</dd></div><div className="flex justify-between"><dt>Frais de plateforme</dt><dd>{formatFCFA(m.serviceFee)}</dd></div><div className="flex justify-between border-t pt-2 font-bold text-lg"><dt>Total</dt><dd>{formatFCFA(m.totalPrice)}</dd></div></dl>{m.accessNotes&&<p className="mt-4 text-sm bg-muted rounded-xl p-3">Accès : {m.accessNotes}</p>}<FileLinks files={m.photos}/><div className="flex flex-wrap gap-2 mt-4">{p.phone?<a className="ap-secondary" href={`tel:${p.phone.replace(/[^+0-9]/g,'')}`}><Phone size={16}/>Appeler</a>:<button className="ap-secondary" onClick={()=>toast.info('Ce profil fictif n’a pas de numéro joignable. Ajoutez votre propre numéro depuis le profil professionnel pour tester l’appel.')}><Phone size={16}/>Appeler (démo)</button>}{pro&&m.location&&<a className="ap-secondary" href={`https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=${p.location.lat}%2C${p.location.lng}%3B${m.location.lat}%2C${m.location.lng}`} target="_blank" rel="noreferrer"><Navigation size={16}/>Itinéraire</a>}</div></section>
 <ServiceMap markers={[{id:p.id,name:`${p.name} · position de démonstration`,point:p.location}]} position={m.location} caption={`Position de démonstration, sans suivi GPS en direct. Délai indicatif : ${p.delaiMoyen}.`}/>
 {pro&&<section className="ap-panel"><h2 className="font-bold mb-4">Actions de la mission</h2><div className="flex gap-3 flex-wrap">{m.status==='en_attente'&&<><button className="ap-button" disabled={busy||p.kyc!=='verifie'||p.suspended||!!m.paymentFlow&&m.paymentFlow.deposit?.status!=='COMPLETED'} onClick={()=>void transition('accept')}>Accepter la mission</button><button className="ap-secondary" disabled={busy} onClick={()=>{if(window.confirm('Refuser cette demande ? Un encaissement confirmé devra ensuite être remboursé.'))void transition('refuse')}}>Refuser</button></>}{m.status==='acceptee'&&<button className="ap-button" disabled={busy} onClick={()=>void transition('route')}>Je suis en route</button>}{m.status==='en_route'&&<button className="ap-button" disabled={busy} onClick={()=>void transition('start')}>Je suis arrivé · Commencer</button>}</div>{m.status==='en_cours'&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();void transition('finish')}}><FileUpload imagesOnly label="Photos avant intervention *" value={before} onChange={setBefore}/><FileUpload imagesOnly label="Photos après intervention *" value={after} onChange={setAfter}/><label className="ap-label">Compte rendu obligatoire<textarea className="ap-input mt-2" required rows={3} value={report} onChange={e=>setReport(e.target.value)}/></label><button className="ap-button" disabled={busy||!before.length||!after.length||!report.trim()}>Terminer l’intervention</button></form>}{['a_valider','validee','payee','annulee','litige'].includes(m.status)&&<p className="text-sm text-muted-foreground">{m.status==='litige'?'L’administrateur examine le litige. Le paiement reste bloqué.':m.status==='a_valider'?'En attente de validation du client.':'Aucune action d’intervention requise.'}</p>}</section>}
 {m.report&&<section className="ap-panel"><h2 className="font-bold mb-3">Compte rendu d’intervention</h2><p className="text-sm mb-4">{m.report}</p><h3 className="font-semibold text-sm mb-2">Avant</h3><FileLinks files={m.before}/><h3 className="font-semibold text-sm mt-4 mb-2">Après</h3><FileLinks files={m.after}/>{!m.before.length&&!m.after.length&&<p className="text-xs text-muted-foreground">Mission préchargée de démonstration, sans photos justificatives.</p>}</section>}
 {client&&m.status==='a_valider'&&<section className="ap-panel bg-emerald-50"><h2 className="font-bold mb-3">Votre intervention est-elle terminée ?</h2><p className="text-sm mb-4">Vérifiez le compte rendu avant d’autoriser le versement de test. La validation ne confirme pas encore le versement.{m.deadline&&` Validation automatique prévue le ${new Date(m.deadline).toLocaleString('fr-FR',{timeZone:'Africa/Libreville',dateStyle:'short',timeStyle:'short'})}, lors du prochain accès à l’application.`}</p><button className="ap-button" disabled={busy} onClick={()=>{if(window.confirm('Confirmer la bonne réalisation et autoriser le versement de test ?'))void transition('validate')}}>Valider et autoriser le versement</button></section>}
 {client&&m.status==='en_attente'&&<button className="ap-secondary" disabled={busy} onClick={()=>{if(window.confirm('Annuler cette demande ? Si le paiement est confirmé, lancez ensuite le remboursement dans le bloc Paiement.'))void transition('cancel')}}>Annuler la demande</button>}
 {client&&['acceptee','en_route','en_cours','a_valider'].includes(m.status)&&<section className="ap-panel"><button className="text-red-700 font-semibold" onClick={()=>setShowDispute(!showDispute)}>Signaler un problème avec la mission</button>{showDispute&&<form className="mt-4 space-y-4" onSubmit={async e=>{e.preventDefault();const r=await act({type:'dispute',missionId:id,reason,evidence});if(r.ok){toast.success('Litige ouvert. Le paiement reste bloqué.');setShowDispute(false)}}}><label className="ap-label">Décrivez le problème<textarea className="ap-input mt-2" value={reason} onChange={e=>setReason(e.target.value)} required rows={3}/></label><FileUpload label="Preuves (facultatif)" value={evidence} onChange={setEvidence}/><button className="ap-button" disabled={busy}>Ouvrir un litige et bloquer le paiement</button></form>}</section>}
 {m.dispute&&<section className="ap-panel border-red-200"><h2 className="font-bold text-red-800 mb-3">Dossier de litige</h2><p className="text-sm mb-3">{m.dispute.reason}</p><FileLinks files={m.dispute.evidence}/>{m.dispute.decision&&<p className="text-sm mt-3">Décision : {m.dispute.decision}</p>}{admin&&m.status==='litige'&&<form className="space-y-4 mt-5" onSubmit={async e=>{e.preventDefault();if(!window.confirm('Confirmer cette décision définitive pour la démonstration ?'))return;const r=await act({type:'resolve',missionId:id,decision,reason});if(r.ok)toast.success('Décision enregistrée.')}}><p className="text-sm">Examinez le compte rendu, les pièces jointes et la conversation ci-dessous.</p><label className="ap-label">Décision<select className="ap-input mt-2" value={decision} onChange={e=>setDecision(e.target.value as 'refund'|'release')}><option value="refund">Autoriser le remboursement (test)</option><option value="release">Autoriser le versement au professionnel (test)</option></select></label><label className="ap-label">Justification<textarea className="ap-input mt-2" required value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="ap-button" disabled={busy}>Confirmer la décision</button></form>}</section>}
 {client&&['validee','payee'].includes(m.status)&&!m.review&&<form className="ap-panel space-y-4" onSubmit={async e=>{e.preventDefault();const r=await act({type:'review',missionId:id,quality,punctuality,communication,comment});if(r.ok)toast.success('Merci pour votre avis.')}}><h2 className="font-bold">Évaluez cette intervention</h2>{[{label:'Qualité du travail',value:quality,set:setQuality},{label:'Ponctualité',value:punctuality,set:setPunctuality},{label:'Communication',value:communication,set:setCommunication}].map(r=><label className="ap-label" key={r.label}>{r.label}<select className="ap-input mt-2" value={r.value} onChange={e=>r.set(Number(e.target.value))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label>)}<label className="ap-label">Votre commentaire<textarea className="ap-input mt-2" required value={comment} onChange={e=>setComment(e.target.value)}/></label><button className="ap-button" disabled={busy}>Publier mon avis</button></form>}
 {m.review&&<section className="ap-panel"><h2 className="font-bold">Avis enregistré</h2><p className="text-sm mt-2">{m.review.hidden?'Cet avis a été masqué par la modération.':m.review.comment}</p></section>}
 </div><aside className="space-y-5"><section className="ap-panel"><h2 className="font-bold mb-5">Historique de la mission</h2><ol className="space-y-5">{m.events.map((e,i)=><li key={i} className="flex gap-3"><CheckCircle2 className="text-emerald-dark shrink-0" size={18}/><div><p className="text-sm font-medium">{e.text}</p><p className="text-xs text-muted-foreground mt-1">{new Date(e.at).toLocaleString('fr-FR',{timeZone:'Africa/Libreville',dateStyle:'short',timeStyle:'short'})}</p></div></li>)}</ol></section><ChatThread thread={id}/></aside></div></div>
}
