'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {CheckCircle2,ShieldCheck,ArrowLeft,ArrowRight,BadgeCheck,MapPin} from 'lucide-react'
import Image from '@/components/smart-image'
import {toast} from 'sonner'
import {type Professional,formatFCFA,quartiers} from '@/lib/data'
import type {FileRef,Point} from '@/lib/marketplace'
import {useWorkspace,WorkspaceLoading} from '@/components/workspace-provider'
import {PageHeading,RoleGuard} from '@/components/market-ui'
import {FileUpload} from '@/components/file-upload'
import {ServiceMap} from '@/components/service-map'
import {PaymentPanel} from '@/components/payment-panel'
import type {PaymentConfig} from '@/lib/payment-types'
export function ReserverClient({pro}:{pro:Professional}){
 const {state,act,busy}=useWorkspace();const router=useRouter();const [step,setStep]=useState(1);const [proId,setProId]=useState(pro.id);const [service,setService]=useState('');const [description,setDescription]=useState('');const [urgent,setUrgent]=useState(true);const [date,setDate]=useState('');const [time,setTime]=useState('');const [address,setAddress]=useState('');const [quartier,setQuartier]=useState('Libreville Centre');const [accessNotes,setAccessNotes]=useState('');const [location,setLocation]=useState<Point|null>(null);const [photos,setPhotos]=useState<FileRef[]>([]);const [paymentMethod,setPaymentMethod]=useState<'airtel'|'moov'>('airtel');const [phone,setPhone]=useState('');const [confirmation,setConfirmation]=useState('');const [requestKey,setRequestKey]=useState('');const [auto,setAuto]=useState(false)
 const [paymentConfig,setPaymentConfig]=useState<PaymentConfig|null>(null)
 useEffect(()=>{setRequestKey(crypto.randomUUID());fetch('/api/payments/config',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Configuration des paiements indisponible.');setPaymentConfig(await r.json())}).catch(e=>{console.error(e);toast.error('Impossible de charger les moyens de paiement. Actualisez la page.')})},[])
 if(!state)return <WorkspaceLoading/>
 const current=state.pros.find(p=>p.id===proId)||pro
 const options=state.pros.filter(p=>p.categorie===pro.categorie&&p.kyc==='verifie'&&!p.suspended&&p.zones.includes(quartier)&&(!urgent||p.enLigne)&&p.services.some(s=>s.nom===service)).sort((a,b)=>b.note-a.note)
 const base=current.services.find(s=>s.nom===service)?.tarif||0;const fee=Math.round(base*state.commission/100)
 function next(){if(step===1&&!service){toast.error('Choisissez un service.');return}if(step===2){if(!description.trim()){toast.error('Décrivez votre besoin.');return}if(!urgent&&(!date||!time||new Date(`${date}T${time}:00+01:00`)<=new Date())){toast.error('Choisissez une date et une heure à venir.');return}}if(step===3&&(!address.trim()||!quartier)){toast.error('Indiquez votre adresse et votre quartier.');return}if(step===4&&!options.some(p=>p.id===proId)){toast.error('Sélectionnez un professionnel vérifié disponible pour ce service.');return}setStep(step+1)}
 if(confirmation)return <div className="ap-client-page !max-w-2xl text-center !py-12"><CheckCircle2 size={64} className="text-emerald-dark mx-auto mb-5"/><h1 className="text-2xl font-bold">Votre demande est enregistrée</h1><p className="text-muted-foreground my-4">Mission {confirmation}. Finalisez maintenant le paiement de test ci-dessous. La réservation seule ne confirme aucun encaissement.</p><div className="text-left my-6">{state.missions.find(m=>m.id===confirmation)&&<PaymentPanel mission={state.missions.find(m=>m.id===confirmation)!}/>}</div><Link className="ap-button" href={`/reservations/${confirmation}`}>Suivre ma mission</Link></div>
 return <main className="ap-client-page"><PageHeading title="Votre prochain coup de main" subtitle={`Réservez votre intervention · Étape ${step}/5 · ${['Le service','Votre besoin','Votre adresse','Votre professionnel','Récapitulatif et paiement'][step-1]}`}/><RoleGuard role="client">
 <ol aria-label="Étapes de réservation" className="mb-8 grid grid-cols-5 gap-2 sm:gap-4">{['Service','Besoin','Adresse','Professionnel','Paiement'].map((label,i)=><li key={label} aria-current={step===i+1?'step':undefined} className="min-w-0"><div className={`mb-3 h-1.5 rounded-full ${i+1<=step?'bg-primary':'bg-primary/15'}`}/><div className="flex flex-col items-center gap-2 sm:flex-row"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-bold ${i+1<=step?'bg-primary text-white':'bg-white text-muted-foreground'}`}>{i+1<step?<CheckCircle2 size={17}/>:i+1}</span><span className={`sr-only text-xs font-semibold sm:not-sr-only ${i+1===step?'text-primary':'text-muted-foreground'}`}>{label}</span></div></li>)}</ol>
 <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="ap-booking-panel space-y-5">

 {step===1&&<><h2 className="text-lg font-bold">De quel service avez-vous besoin ?</h2>{current.services.map(s=><label key={s.nom} className={`grid grid-cols-[18px_minmax(0,1fr)] sm:grid-cols-[18px_minmax(0,1fr)_auto] gap-3 items-center p-4 rounded-2xl border cursor-pointer transition-colors ${service===s.nom?'border-emerald-600 bg-emerald-50':'border-border'}`}><input type="radio" name="service" checked={service===s.nom} onChange={()=>setService(s.nom)}/><span className="flex-1">{s.nom}</span><strong className="col-start-2 text-sm text-primary sm:col-start-auto">{formatFCFA(s.tarif)}</strong></label>)}</>}
 {step===2&&<><label className="ap-label">Décrivez votre besoin<textarea className="ap-input mt-2" rows={4} maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Quel est le problème ? Depuis quand ? Précisez ce qui aidera le professionnel à préparer l’intervention."/></label><FileUpload imagesOnly label="Photos du besoin (facultatif)" value={photos} onChange={setPhotos}/><div className="flex gap-3"><button className={urgent?'ap-button flex-1':'ap-secondary flex-1'} onClick={()=>setUrgent(true)}>Urgence</button><button className={!urgent?'ap-button flex-1':'ap-secondary flex-1'} onClick={()=>setUrgent(false)}>Planifier</button></div>{!urgent&&<div className="grid grid-cols-1 min-[400px]:grid-cols-2 gap-3"><label className="ap-label">Date<input className="ap-input mt-2" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="ap-label">Heure (Gabon)<input className="ap-input mt-2" type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div>}</>}
 {step===3&&<><label className="ap-label">Adresse d’intervention<input className="ap-input mt-2" value={address} onChange={e=>setAddress(e.target.value)} placeholder="Rue, résidence, repère connu…"/></label><label className="ap-label">Quartier<select className="ap-input mt-2" value={quartier} onChange={e=>setQuartier(e.target.value)}>{quartiers.map(q=><option key={q}>{q}</option>)}</select></label><ServiceMap position={location} onSelect={setLocation} caption="Repère d’intervention facultatif ; l’adresse écrite reste obligatoire."/><label className="ap-label">Instructions d’accès (facultatif)<textarea className="ap-input mt-2" rows={2} value={accessNotes} onChange={e=>setAccessNotes(e.target.value)} placeholder="Portail, étage, point de rencontre…"/></label></>}
 {step===4&&<><h2 className="font-bold">Qui interviendra chez vous ?</h2><label className="flex gap-3 rounded-xl bg-amber-50 p-4 text-sm"><input type="checkbox" checked={auto} onChange={e=>{setAuto(e.target.checked);if(e.target.checked&&options[0])setProId(options[0].id)}}/><span>Laisser Allo-Pro choisir le mieux noté parmi les professionnels vérifiés proposant ce service{urgent?' et disponibles':''}.</span></label>{!options.length&&<p className="text-amber-900">Aucun professionnel disponible. Revenez à l’étape 2 pour planifier l’intervention.</p>}{options.map(p=><label key={p.id} className={`grid grid-cols-[18px_minmax(0,1fr)] sm:grid-cols-[18px_minmax(0,1fr)_auto] items-center gap-3 p-4 rounded-2xl border cursor-pointer ${proId===p.id?'bg-emerald-50 border-emerald-600':'border-border'}`}><input type="radio" name="pro" checked={proId===p.id} onChange={()=>{setProId(p.id);setAuto(false)}}/><div><p className="font-bold">{p.name}</p><p className="text-sm text-muted-foreground">Vérifié · {p.zone} · {p.note}/5</p></div><strong className="col-start-2 text-sm text-primary sm:col-start-auto">{formatFCFA(p.services.find(s=>s.nom===service)!.tarif)}</strong></label>)}</>}
 {step===5&&<><div className="space-y-3"><h2 className="font-bold text-lg">Tout est prêt ?</h2><p>{current.name} · {service}</p><p className="text-sm text-muted-foreground">{description}</p><p className="text-sm">{address}, {quartier}<br/>{urgent?'Dès que possible':`${date} à ${time} (Gabon)`}</p><div className="border-t border-border pt-3 flex justify-between"><span>Prestation estimée</span><strong>{formatFCFA(base)}</strong></div><div className="flex justify-between text-sm"><span>Frais de plateforme ({state.commission} %)</span><span>{formatFCFA(fee)}</span></div><div className="flex flex-wrap justify-between gap-2 rounded-2xl bg-primary/5 p-4 text-xl font-bold text-primary"><span>Total estimé</span><span>{formatFCFA(base+fee)}</span></div><p className="text-xs text-muted-foreground">Aucun supplément automatique. Toute prestation complémentaire doit faire l’objet d’un accord préalable.</p></div><fieldset><legend className="font-semibold mb-3">Paiement Mobile Money via pawaPay (test)</legend><div className="grid grid-cols-1 min-[400px]:grid-cols-2 gap-3">{(['airtel','moov'] as const).map(m=><label key={m} className={`rounded-xl p-4 border flex gap-2 ${paymentMethod===m?'bg-emerald-50 border-emerald-600':'border-border'}`}><input type="radio" name="payment" checked={paymentMethod===m} disabled={!paymentConfig?.options.some(o=>o.method===m)} onChange={()=>setPaymentMethod(m)}/><span>{m==='airtel'?'Airtel Money':'Moov Money'}{!paymentConfig?.options.some(o=>o.method===m)&&<small className="block">Non disponible</small>}</span></label>)}</div></fieldset><label className="ap-label">Numéro Mobile Money de test<input type="tel" className="ap-input mt-2" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="074345678"/></label><div className="bg-emerald-50 rounded-xl p-4 text-sm text-emerald-950"><ShieldCheck size={20} className="mb-2"/>Le versement au professionnel nécessite un encaissement confirmé et la validation de la mission. Un litige bloque tout versement.<strong className="block mt-2">{paymentConfig?.message||'Chargement des moyens de paiement…'}</strong><p className="mt-2">Aucun séquestre bancaire. Moov Gabon n’est proposé via pawaPay que si votre compte le déclare disponible ; sans clé, il reste une simulation locale.</p></div></>}
 <div className="flex flex-wrap gap-3 border-t border-border/60 pt-5"><button className="ap-secondary" disabled={busy} onClick={()=>step>1?setStep(step-1):router.back()}><ArrowLeft size={16}/>Retour</button>{step<5?<button className="ap-button flex-1" onClick={next}>Continuer<ArrowRight size={17}/></button>:<button className="ap-button min-w-0 flex-1 !bg-gold !text-slate-950 hover:!bg-gold-dark" disabled={busy||!requestKey||!paymentConfig?.options.some(o=>o.method===paymentMethod)} onClick={async()=>{const res=await act({type:'book',proId,service,description,address,quartier,accessNotes,date:urgent?'':`${date}T${time}:00+01:00`,urgent,paymentMethod,phone:phone.replace(/\s/g,''),photos,location,requestKey});if(res.ok)setConfirmation(res.result!)} }>{busy?'Enregistrement…':'Réserver et passer au paiement'}</button>}</div></div>
 <aside className="space-y-4 lg:sticky lg:top-24"><div className="rounded-3xl border border-border/40 bg-white p-6 shadow-sm"><p className="ap-eyebrow mb-5">Votre intervention</p><div className="flex items-center gap-3"><div className="relative aspect-square w-14 shrink-0 overflow-hidden rounded-2xl bg-muted"><Image src={current.photo} alt={`Portrait illustratif de ${current.name}`} fill sizes="56px" className="object-cover"/></div><div className="min-w-0"><p className="text-sm font-bold">{current.name}</p><p className="mt-1 text-xs text-muted-foreground">{current.metier}</p></div></div>{current.verifie&&<p className="mt-4 flex items-center gap-1.5 text-xs font-semibold text-primary"><BadgeCheck size={15}/>Professionnel vérifié</p>}<div className="my-5 border-t border-border/60"/><p className="text-sm font-semibold">{service||'Votre service à sélectionner'}</p><p className="mt-2 flex items-start gap-1.5 text-xs text-muted-foreground"><MapPin size={15} className="shrink-0"/>{quartier}</p>{service?<div className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-3 text-muted-foreground"><span>Prestation</span><span className="whitespace-nowrap">{formatFCFA(base)}</span></div><div className="flex justify-between gap-3 text-muted-foreground"><span>Frais ({state.commission} %)</span><span className="whitespace-nowrap">{formatFCFA(fee)}</span></div><div className="flex flex-wrap justify-between gap-2 border-t border-border/60 pt-4 font-bold text-primary"><span>Total estimé</span><span>{formatFCFA(base+fee)}</span></div></div>:<p className="mt-4 text-xs leading-relaxed text-muted-foreground">Sélectionnez un service pour afficher le détail du montant estimé, frais inclus.</p>}</div><div className="rounded-3xl bg-primary/5 p-6"><ShieldCheck size={23} className="mb-3 text-primary"/><h2 className="text-sm font-bold">Vous gardez le contrôle</h2><p className="mt-2 text-xs leading-6 text-muted-foreground">Vérifiez le récapitulatif avant de confirmer. Aucun supplément automatique. Un litige bloque le paiement.</p><p className="mt-3 text-xs font-semibold text-primary">Démonstration · Aucun paiement réel</p></div></aside>
 </div></RoleGuard></main>
}
