'use client'
import {useState} from 'react'
import Link from 'next/link'
import {toast} from 'sonner'
import {useWorkspace,WorkspaceLoading} from './workspace-provider'
import {PageHeading,RoleGuard,MissionCard,Empty} from './market-ui'
import {FileLinks} from './file-upload'
import {PaymentSettings} from './payment-settings'
import {formatFCFA} from '@/lib/data'
export function AdminDashboard(){
 const {state,act,busy}=useWorkspace();const [tab,setTab]=useState('vue');const [reason,setReason]=useState('');const [selected,setSelected]=useState('');const [category,setCategory]=useState('');const [query,setQuery]=useState('')
 if(!state)return <WorkspaceLoading/>
 const pending=state.pros.filter(p=>p.kyc==='en_cours');const disputes=state.missions.filter(m=>m.status==='litige');const selectedPro=state.pros.find(p=>p.id===selected)
 return <div className="ap-page"><PageHeading title="Administration" subtitle="Supervision de votre démonstration privée. Ces actions ne donnent aucun accès aux comptes d’autres utilisateurs."/><RoleGuard role="administrateur"><div className="ap-tabs">{[{id:'vue',label:'Vue d’ensemble'},{id:'pros',label:`Professionnels (${pending.length} à vérifier)`},{id:'missions',label:'Missions'},{id:'litiges',label:`Litiges (${disputes.length})`},{id:'catalogue',label:'Catalogue'},{id:'moderation',label:'Comptes et avis'},{id:'parametres',label:'Commissions'},{id:'paiements',label:'Paiements pawaPay'}].map(t=><button key={t.id} className={tab===t.id?'ap-button':'ap-secondary'} onClick={()=>setTab(t.id)}>{t.label}</button>)}</div>
 {tab==='vue'&&<><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[{label:'Profils de démonstration',value:state.pros.length+2},{label:'Professionnels vérifiés',value:state.pros.filter(p=>p.kyc==='verifie'&&!p.suspended).length},{label:'Missions',value:state.missions.length},{label:'Litiges ouverts',value:disputes.length}].map(s=><div key={s.label} className="ap-panel"><strong className="text-3xl text-emerald-dark">{s.value}</strong><p className="text-sm mt-3 text-muted-foreground">{s.label}</p></div>)}</div><div className="grid md:grid-cols-3 gap-4 mt-4">{[{label:'Encaissements de test non remboursés',value:state.missions.filter(m=>['bloque','a_verser','a_rembourser','libere'].includes(m.payment)).reduce((v,m)=>v+m.totalPrice,0)},{label:'Montants simulés bloqués',value:state.missions.filter(m=>m.payment==='bloque').reduce((v,m)=>v+m.totalPrice,0)},{label:'Frais de plateforme acquis (démo)',value:state.missions.filter(m=>m.payment==='libere').reduce((v,m)=>v+m.serviceFee,0)}].map(s=><div className="ap-panel" key={s.label}><strong className="text-xl">{formatFCFA(s.value)}</strong><p className="text-sm text-muted-foreground mt-2">{s.label}</p></div>)}</div><div className="ap-panel mt-6"><h2 className="font-bold mb-2">Priorités du jour</h2><p className="text-muted-foreground">{pending.length} dossier(s) à contrôler et {disputes.length} litige(s) à arbitrer. Les paiements en litige restent bloqués.</p></div></>}
 {tab==='pros'&&<div className="grid md:grid-cols-2 gap-4">{state.pros.map(p=><div key={p.id} className="ap-panel"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{p.name}</h2><p className="text-sm text-muted-foreground">{p.categorie} · {p.zone}</p></div><span className="text-xs text-emerald-dark font-semibold">{({verifie:'Vérifié',brouillon:'Brouillon',en_cours:'À vérifier',refuse:'Refusé'})[p.kyc]}</span></div><p className="text-sm mt-3">{p.bio}</p><div className="flex flex-wrap gap-2 mt-4"><button className="ap-secondary" onClick={()=>{setSelected(selected===p.id?'':p.id);setReason('')}}>Examiner le dossier</button><button className="ap-secondary" disabled={busy} onClick={()=>void act({type:'suspend',proId:p.id,suspended:!p.suspended})}>{p.suspended?'Réactiver':'Suspendre'}</button></div>{selectedPro?.id===p.id&&<div className="mt-4 border-t pt-4 space-y-3"><p className="text-sm">Expérience : {p.experience} ans · Zones : {p.zones.join(', ')}</p>{Object.entries(p.documents).map(([kind,files])=><div key={kind}><strong className="text-sm">{kind}</strong><FileLinks files={files}/></div>)}{!Object.keys(p.documents).length&&<p className="text-xs text-muted-foreground">Profil fictif prévalidé : aucune pièce d’identité réelle enregistrée.</p>}<label className="ap-label">Motif de décision<textarea className="ap-input mt-2" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Obligatoire en cas de refus"/></label><div className="flex gap-2"><button className="ap-button" disabled={busy||p.kyc!=='en_cours'} onClick={async()=>{const r=await act({type:'kyc',proId:p.id,approve:true,reason});if(r.ok)toast.success('Dossier validé')}}>Approuver</button><button className="ap-secondary" disabled={busy||p.kyc!=='en_cours'||!reason.trim()} onClick={()=>void act({type:'kyc',proId:p.id,approve:false,reason})}>Refuser</button></div></div>}</div>)}</div>}
 {tab==='missions'&&<><label className="ap-label">Rechercher une mission<input className="ap-input mt-2 mb-4" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Identifiant, service ou quartier"/></label><div className="grid md:grid-cols-2 gap-4">{state.missions.filter(m=>`${m.id} ${m.service} ${m.quartier}`.toLowerCase().includes(query.toLowerCase())).map(m=><MissionCard key={m.id} mission={m}/>)}</div><p className="text-xs text-muted-foreground mt-4">L’administrateur arbitre les litiges ; il ne contourne pas les transitions et la validation du client.</p></>}
 {tab==='litiges'&&(disputes.length?<div className="space-y-4">{disputes.map(m=><div className="ap-panel" key={m.id}><MissionCard mission={m}/><p className="my-3 text-sm">{m.dispute?.reason}</p><FileLinks files={m.dispute?.evidence||[]}/><Link href={`/reservations/${m.id}`} className="ap-button mt-4">Examiner les preuves et décider</Link></div>)}</div>:<Empty text="Aucun litige ouvert."/>)}
 {tab==='catalogue'&&<div className="ap-panel"><h2 className="font-bold mb-4">Catégories de services</h2><form className="flex gap-2 mb-5" onSubmit={async e=>{e.preventDefault();const r=await act({type:'category',name:category,active:true});if(r.ok)setCategory('')}}><input aria-label="Nouvelle catégorie" className="ap-input" required value={category} onChange={e=>setCategory(e.target.value)} placeholder="Nouvelle catégorie"/><button className="ap-button" disabled={busy}>Ajouter</button></form><div className="space-y-3">{state.categories.map(c=><div key={c.name} className="flex justify-between items-center border-t pt-3"><span>{c.name}</span><button className="ap-secondary" disabled={busy} onClick={()=>void act({type:'category',name:c.name,active:!c.active})}>{c.active?'Désactiver':'Activer'}</button></div>)}</div><h2 className="font-bold mt-8 mb-3">Services proposés par les professionnels</h2>{state.pros.map(p=><details key={p.id} className="border-t py-3"><summary className="cursor-pointer font-medium">{p.name} · {p.services.length} services</summary><AdminServices proId={p.id} services={p.services}/></details>)}</div>}
 {tab==='moderation'&&<div className="space-y-5"><div className="ap-panel"><h2 className="font-bold">Compte client de la démonstration</h2><p className="my-3">{state.profile.name} — {state.clientSuspended?'Suspendu':'Actif'}</p><button className="ap-secondary" disabled={busy} onClick={()=>void act({type:'clientSuspend',suspended:!state.clientSuspended})}>{state.clientSuspended?'Réactiver':'Suspendre le client'}</button></div><div className="ap-panel"><h2 className="font-bold mb-4">Avis clients</h2>{state.missions.filter(m=>m.review).map(m=><div key={m.id} className="border-t py-3"><p>{m.review?.comment}</p><p className="text-xs text-muted-foreground">{m.id} · {m.review?.hidden?'Masqué':'Publié'}</p><button className="ap-secondary mt-2" disabled={busy} onClick={()=>void act({type:'moderate',missionId:m.id,hidden:!m.review?.hidden})}>{m.review?.hidden?'Republier':'Masquer'}</button></div>)}{!state.missions.some(m=>m.review)&&<p className="text-sm text-muted-foreground">Aucun nouvel avis dans votre démonstration.</p>}</div><div className="ap-panel"><h2 className="font-bold mb-4">Signalements</h2>{state.reports.map(r=><div key={r.id} className="border-t py-3"><p className="font-semibold">{r.target}</p><p className="text-sm my-2">{r.reason}</p><button className="ap-secondary" disabled={busy||r.resolved} onClick={()=>void act({type:'resolveReport',reportId:r.id})}>{r.resolved?'Traité':'Marquer comme traité'}</button></div>)}{!state.reports.length&&<p className="text-sm text-muted-foreground">Aucun signalement.</p>}</div></div>}
 {tab==='paiements'&&<PaymentSettings/>}
 {tab==='parametres'&&<form className="ap-panel space-y-5 max-w-xl" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await act({type:'settings',commission:Number(f.get('commission')),autoHours:Number(f.get('autoHours'))});if(r.ok)toast.success('Paramètres enregistrés pour les prochaines missions.')}}><h2 className="font-bold">Commissions et validation automatique</h2><label className="ap-label">Frais de plateforme (%)<input name="commission" type="number" min={0} max={30} step="0.1" defaultValue={state.commission} className="ap-input mt-2" required/></label><label className="ap-label">Délai de validation automatique (heures)<input name="autoHours" type="number" min={1} max={720} defaultValue={state.autoHours} className="ap-input mt-2" required/></label><p className="text-sm text-muted-foreground">Les nouveaux frais s’appliquent aux nouvelles réservations. Le délai est fixé au moment de la fin d’intervention. Dans la démo, les échéances sont traitées lors des accès à l’application, jamais en cas de litige. Aucun traitement planifié en arrière-plan n’est activé.</p><button className="ap-button" disabled={busy}>Enregistrer</button></form>}
 </RoleGuard></div>
}

function AdminServices({proId,services:initial}:{proId:string;services:{nom:string;tarif:number}[]}){
 const {act,busy}=useWorkspace();const [services,setServices]=useState(initial)
 return <form className="mt-4 space-y-3" onSubmit={async e=>{e.preventDefault();const r=await act({type:'adminServices',proId,services});if(r.ok)toast.success('Services mis à jour pour les prochaines réservations.')}}>{services.map((s,i)=><div key={i} className="flex flex-wrap gap-2"><input required aria-label={`Nom du service ${i+1}`} className="ap-input flex-1 min-w-40" value={s.nom} onChange={e=>setServices(services.map((v,j)=>i===j?{...v,nom:e.target.value}:v))}/><input required aria-label={`Tarif du service ${i+1} en FCFA`} className="ap-input w-32" type="number" min={1} max={10000000} value={s.tarif} onChange={e=>setServices(services.map((v,j)=>i===j?{...v,tarif:Number(e.target.value)}:v))}/><button type="button" className="text-red-700 text-sm" disabled={services.length===1} onClick={()=>setServices(services.filter((_,j)=>j!==i))}>Retirer</button></div>)}<div className="flex flex-wrap gap-3"><button type="button" className="ap-secondary" disabled={services.length>=20} onClick={()=>setServices([...services,{nom:'',tarif:1000}])}>Ajouter un service</button><button className="ap-button" disabled={busy}>Enregistrer les services</button></div></form>
}
