'use client'
import Link from 'next/link'
import {ArrowLeft,CheckCircle2,ShieldCheck} from 'lucide-react'
import {statusLabels,type Mission,type Role} from '@/lib/marketplace'
import {formatFCFA} from '@/lib/data'
import {useWorkspace} from './workspace-provider'
export function PageHeading({title,subtitle,back}:{title:string;subtitle?:string;back?:string}){return <header className="mb-6">{back&&<Link href={back} className="inline-flex gap-2 items-center text-sm text-emerald-dark mb-4"><ArrowLeft size={16}/>Retour</Link>}<p className="text-xs uppercase tracking-[0.2em] font-semibold text-emerald-dark mb-2">Allo Pro · Libreville</p><h1 className="text-2xl md:text-3xl font-bold tracking-tight font-display">{title}</h1>{subtitle&&<p className="text-muted-foreground mt-2 text-sm leading-relaxed">{subtitle}</p>}</header>}
export function StatusBadge({status}:{status:Mission['status']}){return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${status==='litige'?'bg-red-50 text-red-800':status==='annulee'?'bg-gray-100 text-gray-700':status==='en_route'?'bg-amber-100 text-amber-900':'bg-emerald-50 text-emerald-900'}`}>{statusLabels[status]}</span>}
export function Empty({text,href,label}:{text:string;href?:string;label?:string}){return <div className="ap-panel text-center py-10"><CheckCircle2 className="mx-auto text-emerald-dark mb-3" size={30}/><p className="text-muted-foreground">{text}</p>{href&&<Link className="ap-button mt-4" href={href}>{label||'Rechercher un professionnel'}</Link>}</div>}
export function RoleGuard({role,children}:{role:Role;children:React.ReactNode}){const {state}=useWorkspace();if(state?.role!==role)return <div className="ap-panel"><ShieldCheck className="text-emerald-dark mb-3"/><h2 className="font-bold">Espace réservé</h2><p className="mt-2">Sélectionnez le rôle « {role} » dans le bandeau de démonstration pour accéder à cet espace.</p></div>;return <>{children}</>}
export function MissionCard({mission}:{mission:Mission}){const {state}=useWorkspace();const p=state?.pros.find(p=>p.id===mission.professionalId);return <Link href={`/reservations/${mission.id}`} className="ap-panel block hover:shadow-md transition-shadow"><div className="flex justify-between gap-3 flex-wrap mb-3"><span className="font-mono text-xs text-muted-foreground">{mission.id}</span><StatusBadge status={mission.status}/></div><h3 className="font-semibold">{mission.service}</h3><p className="text-sm text-muted-foreground mt-1">{p?.name} · {mission.quartier}</p><p className="text-xs text-muted-foreground mt-2">{mission.address} · {mission.urgent?'Urgent':'Planifié'}</p><p className="text-sm line-clamp-2 mt-2">{mission.description}</p><div className="flex justify-between flex-wrap gap-2 mt-4"><span className="text-sm">{new Date(mission.date).toLocaleString('fr-FR',{timeZone:'Africa/Libreville',dateStyle:'short',timeStyle:'short'})}</span><strong className="text-emerald-dark">{formatFCFA(mission.totalPrice)}</strong></div></Link>}
