'use client'
import {useState} from 'react'
import {toast} from 'sonner'
import {useWorkspace,WorkspaceLoading} from './workspace-provider'
import {PageHeading,RoleGuard} from './market-ui'
import {FileUpload} from './file-upload'
import {LocationPicker} from './location-picker'
import {CatalogueExplorer,type CatalogueExplorerValue} from './catalogue-explorer'
import {quartiers} from '@/lib/data'
import type {Pro,FileRef} from '@/lib/marketplace'
export function ProDossier(){const {state}=useWorkspace();if(!state)return <WorkspaceLoading/>;const pro=state.pros.find(p=>p.id===state.activeProId)!;return <div className="ap-page max-w-3xl"><PageHeading title="Mon dossier professionnel" back="/espace-pro" subtitle="Vos pièces restent privées. Pour cette démonstration, utilisez uniquement des documents fictifs."/><RoleGuard role="professionnel"><DossierForm key={pro.id} pro={pro}/></RoleGuard></div>}
function DossierForm({pro}:{pro:Pro}){
 const {state,act,busy}=useWorkspace();const [step,setStep]=useState(1);const [name,setName]=useState(pro.name);const [bio,setBio]=useState(pro.bio);const [zone,setZone]=useState(pro.zone);const [zones,setZones]=useState(pro.zones);const [provinceId,setProvinceId]=useState<string|null>(pro.provinceId??null);const [cityId,setCityId]=useState<string|null>(pro.cityId??null);const [neighborhoodId,setNeighborhoodId]=useState<string|null>(pro.neighborhoodId??null);const [categorie,setCategorie]=useState(pro.categorie);const [experience,setExperience]=useState(pro.experience);const [phone,setPhone]=useState(pro.phone);const [services,setServices]=useState(pro.services);const [documents,setDocuments]=useState<Record<string,FileRef[]>>(pro.documents);const [catalogueServices,setCatalogueServices]=useState<{id:string;displayName:string}[]>(()=>(pro.serviceIds??[]).map(id=>({id,displayName:'Service enregistré'})))
 async function save(submit:boolean){const r=await act({type:'proProfile',name,bio,zone,zones,provinceId,cityId,neighborhoodId,categorie,experience,phone,services,documents,serviceIds:catalogueServices.map(s=>s.id),submit});if(r.ok)toast.success(submit?'Dossier transmis pour vérification.':'Profil enregistré.')}
 function addCatalogueService(next:CatalogueExplorerValue|null){if(!next?.serviceId)return;if(catalogueServices.some(s=>s.id===next.serviceId)){toast.info('Ce service est déjà dans votre liste.');return}if(catalogueServices.length>=20){toast.error('Vous pouvez sélectionner jusqu’à 20 services du catalogue.');return}setCatalogueServices([...catalogueServices,{id:next.serviceId,displayName:next.displayName||'Service'}])}
 function removeCatalogueService(id:string){setCatalogueServices(catalogueServices.filter(s=>s.id!==id))}
 return <><div className="ap-panel mb-5 flex flex-wrap gap-3 justify-between"><span>Statut : <strong>{({brouillon:'Brouillon',en_cours:'En cours de vérification',verifie:'Vérifié',refuse:'Refusé'})[pro.kyc]}</strong></span>{pro.reason&&<p className="text-red-700 w-full">Motif : {pro.reason}</p>}</div><div className="ap-tabs">{['Informations','Services et zones','Justificatifs'].map((v,i)=><button key={v} onClick={()=>setStep(i+1)} className={step===i+1?'ap-button':'ap-secondary'}>{i+1}. {v}</button>)}</div><form className="ap-panel space-y-5" onSubmit={e=>{e.preventDefault();if(step<3)setStep(step+1);else void save(true)}}>
 {step===1&&<><label className="ap-label">Nom professionnel<input required className="ap-input mt-2" value={name} onChange={e=>setName(e.target.value)}/></label><label className="ap-label">Présentation<textarea required className="ap-input mt-2" rows={4} value={bio} onChange={e=>setBio(e.target.value)}/></label><label className="ap-label">Années d’expérience<input type="number" min={0} max={70} className="ap-input mt-2" value={experience} onChange={e=>setExperience(Number(e.target.value))}/></label><label className="ap-label">Téléphone professionnel (facultatif)<input className="ap-input mt-2" type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Renseigner uniquement un numéro que vous contrôlez"/></label></>}
 {step===2&&<><label className="ap-label">Catégorie<select className="ap-input mt-2" value={categorie} onChange={e=>setCategorie(e.target.value)}>{state?.categories.filter(c=>c.active).map(c=><option key={c.name}>{c.name}</option>)}</select></label><label className="ap-label">Quartier principal<LocationPicker variant="inline" className="mt-2" value={{provinceId,cityId,neighborhoodId,displayName:zone}} onChange={next=>{setZone(next?.displayName||zone);setProvinceId(next?.provinceId??null);setCityId(next?.cityId??null);setNeighborhoodId(next?.neighborhoodId??null)}} placeholder="Votre quartier principal"/></label><fieldset><legend className="ap-label">Zones de déplacement</legend><div className="flex flex-wrap gap-3">{quartiers.map(q=><label key={q} className="text-sm flex items-center gap-2"><input type="checkbox" checked={zones.includes(q)} onChange={()=>setZones(zones.includes(q)?zones.filter(v=>v!==q):[...zones,q])}/>{q}</label>)}</div></fieldset><h2 className="font-semibold">Services et tarifs de départ (FCFA)</h2>{services.map((s,i)=><div key={i} className="flex flex-wrap gap-2"><input aria-label={`Service ${i+1}`} className="ap-input flex-1 min-w-40" value={s.nom} required onChange={e=>setServices(services.map((v,j)=>j===i?{...v,nom:e.target.value}:v))}/><input aria-label={`Tarif du service ${i+1}`} type="number" min={1} max={10000000} className="ap-input w-32" value={s.tarif} required onChange={e=>setServices(services.map((v,j)=>j===i?{...v,tarif:Number(e.target.value)}:v))}/><button className="text-red-700 text-sm px-2" type="button" disabled={services.length===1} onClick={()=>setServices(services.filter((_,j)=>j!==i))}>Retirer</button></div>)}<button type="button" className="ap-secondary" disabled={services.length>=20} onClick={()=>setServices([...services,{nom:'',tarif:1000}])}>Ajouter un service</button><div className="pt-2"><h2 className="font-semibold">Mes services (catalogue)</h2><p className="text-sm text-muted-foreground mt-1">Sélectionnez les services précis que vous proposez pour apparaître dans les recherches ciblées des clients.</p><div className="flex flex-wrap gap-2 mt-3">{catalogueServices.map(s=><span key={s.id} className="inline-flex items-center gap-1.5 rounded-full bg-emerald-dark/10 text-emerald-dark text-xs px-3 py-1"><span className="truncate max-w-[12rem]">{s.displayName}</span><button type="button" aria-label={`Retirer ${s.displayName}`} className="text-emerald-dark/70 hover:text-emerald-dark" onClick={()=>removeCatalogueService(s.id)}>×</button></span>)}</div><div className="mt-3"><CatalogueExplorer variant="popover" value={null} onChange={addCatalogueService} placeholder="+ Ajouter un service"/></div></div></>}
 {step===3&&<>{[{id:'recto',label:'Carte d’identité — recto *'},{id:'verso',label:'Carte d’identité — verso *'},{id:'casier',label:'Casier judiciaire *'},{id:'competence',label:'Certificat de compétence (facultatif)'},{id:'portrait',label:'Portrait professionnel (facultatif)'},{id:'realisations',label:'Galerie de réalisations (facultatif)'}].map(d=><FileUpload key={d.id} imagesOnly={['portrait','realisations'].includes(d.id)} label={d.label} value={documents[d.id]||[]} onChange={f=>setDocuments({...documents,[d.id]:f})}/>)}<p className="text-sm text-muted-foreground">Une modification de votre identité ou de vos justificatifs nécessite une nouvelle validation. Vous ne pourrez pas recevoir de nouvelles missions avant approbation.</p></>}
 <div className="flex gap-3 flex-wrap"><button type="button" disabled={busy} className="ap-secondary" onClick={()=>void save(false)}>Enregistrer le brouillon</button><button disabled={busy||pro.kyc==='en_cours'} className="ap-button flex-1">{step<3?'Continuer':pro.kyc==='en_cours'?'Vérification en cours':'Soumettre mon dossier'}</button></div></form></>
}
