'use client'
import {useState} from 'react'
import Link from 'next/link'
import {Wallet,ClipboardList,BadgeCheck,Settings} from 'lucide-react'
import {useWorkspace,WorkspaceLoading} from './workspace-provider'
import {PageHeading,RoleGuard,MissionCard,Empty} from './market-ui'
import {formatFCFA} from '@/lib/data'
import {paymentLabels} from '@/lib/payment-types'
export function ProDashboard(){const {state,act,busy}=useWorkspace();const [tab,setTab]=useState('nouvelles');if(!state)return <WorkspaceLoading/>;const pro=state.pros.find(p=>p.id===state.activeProId)!;const missions=state.missions.filter(m=>m.professionalId===pro.id);const paid=missions.filter(m=>m.payment==='libere');const current=missions.filter(m=>tab==='nouvelles'?m.status==='en_attente':tab==='encours'?['acceptee','en_route','en_cours','a_valider','litige'].includes(m.status):['validee','payee','annulee'].includes(m.status))
 return <div className="ap-page"><PageHeading title={`Bonjour, ${pro.name.split(' ')[0]}`} subtitle="Votre activité, vos missions et vos revenus au même endroit."/><RoleGuard role="professionnel"><div className="ap-panel mb-6 flex flex-wrap gap-4 justify-between items-center"><div><label className="ap-label">Professionnel de démonstration<select className="ap-input mt-2" value={pro.id} disabled={busy} onChange={e=>void act({type:'role',role:'professionnel',proId:e.target.value})}>{state.pros.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div><label className="flex gap-3 items-center font-semibold"><input type="checkbox" className="w-5 h-5 accent-emerald-700" checked={pro.enLigne} disabled={busy||pro.kyc!=='verifie'||pro.suspended} onChange={e=>void act({type:'availability',available:e.target.checked})}/>{pro.enLigne?'Disponible maintenant':'Indisponible'}</label><p className="text-xs text-muted-foreground mt-2">{pro.kyc==='verifie'?'Identité vérifiée (démo)':'Dossier à compléter ou à valider'}</p></div><Link href="/espace-pro/dossier" className="ap-secondary"><Settings size={16}/>Mon profil et mon dossier</Link></div>
 <div className="grid sm:grid-cols-3 gap-4 mb-8">{[{label:'Gains libérés (simulés)',value:formatFCFA(paid.reduce((v,m)=>v+m.basePrice,0)),icon:Wallet},{label:'Nouvelles demandes',value:missions.filter(m=>m.status==='en_attente').length,icon:ClipboardList},{label:'Missions validées',value:paid.length,icon:BadgeCheck}].map(c=><div className="ap-panel" key={c.label}><c.icon size={24} className="text-emerald-dark mb-4"/><p className="text-2xl font-bold">{c.value}</p><p className="text-sm text-muted-foreground mt-1">{c.label}</p></div>)}</div>
 <h2 className="font-bold text-xl mb-4">Vos missions</h2><div className="ap-tabs">{[{id:'nouvelles',label:'Nouvelles'},{id:'encours',label:'En cours'},{id:'terminees',label:'Terminées / annulées'}].map(t=><button key={t.id} onClick={()=>setTab(t.id)} className={tab===t.id?'ap-button':'ap-secondary'}>{t.label}</button>)}</div><div className="grid md:grid-cols-2 gap-4">{current.map(m=><MissionCard key={m.id} mission={m}/>)}</div>{!current.length&&<Empty text="Aucune mission dans cette rubrique."/>}
 <section className="mt-8"><h2 className="font-bold text-xl mb-4">Historique financier</h2><p className="text-sm text-muted-foreground mb-4">Le client règle la prestation et les frais de plateforme. Après validation, déclenchez le versement depuis la mission. Les gains ne sont comptabilisés qu’après confirmation du versement. Aucun mouvement d’argent réel dans cette démo.</p><div className="ap-panel overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr><th className="p-2">Mission</th><th className="p-2">Prestation</th><th className="p-2">Frais</th><th className="p-2">Paiement</th></tr></thead><tbody>{missions.map(m=><tr key={m.id} className="border-t border-border"><td className="p-2"><Link className="underline" href={`/reservations/${m.id}`}>{m.id}</Link></td><td className="p-2 whitespace-nowrap">{formatFCFA(m.basePrice)}</td><td className="p-2 whitespace-nowrap">{formatFCFA(m.serviceFee)}</td><td className="p-2">{paymentLabels[m.payment]}</td></tr>)}</tbody></table></div></section></RoleGuard></div>
}
