'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {toast} from 'sonner'
import {useWorkspace,WorkspaceLoading} from './workspace-provider'
import {PageHeading} from './market-ui'
import {FileUpload} from './file-upload'
import {ServiceMap} from './service-map'
import {quartiers} from '@/lib/data'
import type {FileRef,Point} from '@/lib/marketplace'
export function ProfileForm({onboarding=false}:{onboarding?:boolean}){const {state}=useWorkspace();if(!state)return <WorkspaceLoading/>;return <ProfileFields key={state.onboarded?'saved':'new'} onboarding={onboarding} initial={state.profile}/>}
function ProfileFields({onboarding,initial}:{onboarding:boolean;initial:NonNullable<ReturnType<typeof useWorkspace>['state']>['profile']}){
 const {act,busy}=useWorkspace();const router=useRouter();const [step,setStep]=useState(1);const [name,setName]=useState(initial.name);const [email,setEmail]=useState(initial.email);const [phone,setPhone]=useState(initial.phone);const [address,setAddress]=useState(initial.address);const [quartier,setQuartier]=useState(initial.quartier);const [photo,setPhoto]=useState<FileRef[]>(initial.photo);const [location,setLocation]=useState<Point|null>(initial.location);const [role,setRole]=useState<'client'|'professionnel'>('client')
 return <div className="ap-page max-w-2xl"><PageHeading title={onboarding?'Bienvenue chez Allo-Pro':'Mes informations'} subtitle={onboarding?`Étape ${step}/3 · Quelques informations pour personnaliser votre expérience.`:'Vos informations sont enregistrées dans votre démonstration privée.'}/><form className="ap-panel space-y-5" onSubmit={async e=>{e.preventDefault();if(onboarding&&step<3){setStep(step+1);return}const r=await act({type:'profile',name,email,phone,address,quartier,photo,location,...(onboarding?{role}:{})});if(r.ok){toast.success('Profil enregistré');router.push(onboarding&&role==='professionnel'?'/espace-pro/dossier':'/accueil')}}}>
 {(!onboarding||step===1)&&<><label className="ap-label">Votre nom<input className="ap-input mt-2" value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/></label><label className="ap-label">E-mail (facultatif)<input className="ap-input mt-2" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="ap-label">Téléphone<input className="ap-input mt-2" type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+241…"/></label><FileUpload label="Photo de profil (facultative)" imagesOnly value={photo} onChange={setPhoto}/></>}
 {(!onboarding||step===2)&&<><label className="ap-label">Quartier<select className="ap-input mt-2" value={quartier} onChange={e=>setQuartier(e.target.value)}>{quartiers.map(q=><option key={q}>{q}</option>)}</select></label><label className="ap-label">Adresse<input className="ap-input mt-2" value={address} onChange={e=>setAddress(e.target.value)}/></label><ServiceMap position={location} onSelect={setLocation} caption="Votre adresse d’intervention. Vous pouvez aussi choisir votre quartier sans charger la carte."/></>}
 {onboarding&&step===3&&<><h2 className="font-bold">Comment souhaitez-vous utiliser Allo-Pro ?</h2>{(['client','professionnel'] as const).map(r=><label key={r} className={`flex gap-3 p-4 rounded-xl border ${role===r?'border-emerald-600 bg-emerald-50':'border-border'}`}><input type="radio" name="role" checked={role===r} onChange={()=>setRole(r)}/><span><strong>{r==='client'?'Je cherche un professionnel':'Je propose mes services'}</strong><small className="block text-muted-foreground mt-1">{r==='client'?'Réservez une intervention en quelques étapes.':'Complétez ensuite votre dossier de vérification.'}</small></span></label>)}</>}
 <div className="flex gap-3">{onboarding&&step>1&&<button type="button" className="ap-secondary" onClick={()=>setStep(step-1)}>Précédent</button>}<button className="ap-button flex-1" disabled={busy}>{onboarding&&step<3?'Continuer':'Enregistrer et continuer'}</button></div></form></div>
}
