import assert from 'node:assert/strict'
import {initialWorkspace} from '../lib/marketplace'
import {applyAction,settleDue} from '../lib/marketplace-engine'
import {applyPaymentStatus} from '../lib/payment-rules'
const now=new Date('2026-09-23T12:00:00Z')
let s=initialWorkspace('Client test','test@example.com',now)
const run=(a:unknown)=>{const r=applyAction(s,a,now);s=r.state;return r.result}
const fail=(a:unknown,match:RegExp)=>assert.throws(()=>applyAction(s,a,now),match)
const booking={type:'book',proId:'1',service:s.pros[0].services[0].nom,description:'Fuite sous évier',address:'Adresse de test',quartier:'Akanda',accessNotes:'',date:'',urgent:true,paymentMethod:'airtel',phone:'077123456',photos:[],location:null,requestKey:'test-rule-1'}
const id=run(booking)!
assert.equal(s.missions[0].totalPrice,8400)
assert.equal(run(booking),id)
assert.equal(s.missions.filter(m=>m.id===id).length,1)
s.missions[0].paymentFlow!.deposit={id:'test-deposit',status:'CREATED'}
applyPaymentStatus(s,s.missions[0],'test-deposit','deposit','COMPLETED',now)
fail({type:'transition',missionId:id,action:'accept'},/autorisée/)
fail({...booking,requestKey:'badzone',quartier:'Franceville'},/quartier/)
fail({...booking,requestKey:'badtime',urgent:false,date:'2020-01-01T09:00:00Z'},/venir/)
run({type:'role',role:'professionnel',proId:'2'})
fail({type:'transition',missionId:id,action:'accept'},/attribuée/)
run({type:'role',role:'professionnel',proId:'1'})
run({type:'transition',missionId:id,action:'accept'})
fail({type:'transition',missionId:id,action:'finish'},/statut/)
run({type:'transition',missionId:id,action:'route'})
run({type:'transition',missionId:id,action:'start'})
fail({type:'transition',missionId:id,action:'finish'},/obligatoires/)
run({type:'transition',missionId:id,action:'finish',before:[{id:'test-before',name:'avant.png'}],after:[{id:'test-after',name:'apres.png'}],report:'Réparation et contrôle effectués.'})
assert.equal(s.missions[0].status,'a_valider')
assert.equal(s.missions[0].payment,'bloque')
run({type:'role',role:'client'})
run({type:'dispute',missionId:id,reason:'La fuite persiste',evidence:[]})
settleDue(s,new Date('2026-10-10T12:00:00Z'))
assert.equal(s.missions[0].payment,'bloque')
fail({type:'transition',missionId:id,action:'validate'},/bloqué/)
fail({type:'resolve',missionId:id,decision:'release',reason:'Test'},/autorisée/)
run({type:'role',role:'administrateur'})
run({type:'resolve',missionId:id,decision:'release',reason:'Intervention complémentaire et preuves examinées.'})
assert.equal(s.missions[0].payment,'a_verser')
assert.equal(s.missions[0].status,'validee')
fail({type:'resolve',missionId:id,decision:'refund',reason:'Test'},/Aucun litige/)
run({type:'role',role:'client'})
run({type:'review',missionId:id,quality:4,punctuality:5,communication:5,comment:'Merci.'})
fail({type:'review',missionId:id,quality:5,punctuality:5,communication:5,comment:'Deuxième avis'},/Un seul avis/)
run({type:'role',role:'professionnel',proId:'1'})
run({type:'proProfile',name:s.pros[0].name+' modifié',bio:'Présentation',zone:'Akanda',zones:['Akanda'],categorie:'Plomberie',experience:5,phone:'',services:s.pros[0].services,documents:{},submit:false})
assert.equal(s.pros[0].kyc,'brouillon')
run({type:'role',role:'client'})
fail({...booking,requestKey:'unverified'},/vérifié/)
run({type:'role',role:'administrateur'})
fail({type:'kyc',proId:'1',approve:true,reason:''},/soumis/)
const fresh=initialWorkspace('Test','test@example.com',now)
assert(settleDue(fresh,new Date('2026-09-26T12:00:00Z')))
assert.equal(fresh.missions.find(m=>m.id==='RES-003')?.payment,'libere')
assert.equal(fresh.missions.find(m=>m.id==='RES-008')?.payment,'bloque')
console.log('RÈGLES MÉTIER : PASS — rôles, vérification, créneaux, zones, idempotence, transitions, preuves, litiges, avis unique, échéances.')
