import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {sessionFetch,BASE} from './auth-smoke.mjs'
let state,version
async function load(){const r=await sessionFetch('/api/workspace');assert.equal(r.status,200);({state,version}=await r.json())}
async function action(a,status=200){const r=await sessionFetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:a,version})});const b=await r.json();assert.equal(r.status,status,JSON.stringify(b));if(r.ok){state=b.state;version=b.version}return b}
const initialLoads=await Promise.all(Array.from({length:5},()=>sessionFetch('/api/workspace')))
assert(initialLoads.every(r=>r.status===200),'Chargements initiaux simultanés')
await load();assert.equal(state.pros.length,10)
assert.equal((await fetch(BASE+'/api/workspace')).status,401)
assert.equal((await fetch(BASE+'/api/files?id=inexistant')).status,401)
const originalVersion=version
await action({type:'favorite',proId:'1'});assert(state.favorites.includes('1'))
let response=await sessionFetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:{type:'favorite',proId:'2'},version:originalVersion})});assert.equal(response.status,409)
const input={type:'book',proId:'1',service:state.pros[0].services[0].nom,description:'Test intégré fuite sous évier',address:'Adresse fictive test',quartier:'Akanda',accessNotes:'Portail vert',date:'',urgent:true,paymentMethod:'airtel',phone:'077123456',photos:[],location:{lat:0.525,lng:9.499},requestKey:crypto.randomUUID()}
const created=await action(input);const missionId=created.result
assert.equal(state.missions[0].totalPrice,8400)
assert.equal((await action(input)).result,missionId)
const payment=await (await sessionFetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'initiate',missionId,kind:'deposit'})})).json()
assert.equal(payment.transaction.mode,'mock','Ce test doit être exécuté sans clé pawaPay')
assert.equal((await sessionFetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'simulate',transactionId:payment.transaction.id,outcome:'COMPLETED'})})).status,200)
await load()
await action({type:'transition',missionId,action:'accept'},400)
await action({type:'role',role:'professionnel',proId:'2'})
await action({type:'transition',missionId,action:'accept'},400)
await action({type:'role',role:'professionnel',proId:'1'})
for(const transition of ['accept','route','start'])await action({type:'transition',missionId,action:transition})
await action({type:'transition',missionId,action:'finish'},400)
const bytes=await readFile(new URL('../public/portraits-v2/pro-1.webp',import.meta.url))
response=await sessionFetch('/api/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'preuve-fictive-test.webp',size:bytes.length,contentType:'image/webp'})})
assert.equal(response.status,200);const upload=await response.json()
response=await fetch(upload.uploadUrl,{method:'PUT',headers:{'Content-Type':'image/webp'},body:bytes});assert.equal(response.status,200)
response=await sessionFetch('/api/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({complete:true,id:upload.id})});assert.equal(response.status,200)
const file=await response.json()
await action({type:'transition',missionId,action:'finish',before:[{id:'not-owned',name:'faux.webp'}],after:[file],report:'Test'},400)
await action({type:'transition',missionId,action:'finish',before:[file],after:[file],report:'Fuite réparée. Test de contrôle terminé.'})
assert.equal(state.missions[0].status,'a_valider')
assert.equal(state.missions[0].payment,'bloque')
await action({type:'message',thread:missionId,text:'Intervention terminée, merci de vérifier.'})
await action({type:'role',role:'client'})
await action({type:'dispute',missionId,reason:'La fuite persiste après intervention.',evidence:[file]})
assert.equal(state.missions[0].payment,'bloque')
await action({type:'transition',missionId,action:'validate'},400)
await action({type:'resolve',missionId,decision:'release',reason:'Test'},400)
await action({type:'role',role:'administrateur'})
await action({type:'resolve',missionId,decision:'release',reason:'Contrôle des pièces et réparation complémentaire effectuée.'})
assert.equal(state.missions[0].payment,'a_verser')
await action({type:'role',role:'client'})
await action({type:'review',missionId,quality:4,punctuality:5,communication:4,comment:'Intervention test validée.'})
await action({type:'review',missionId,quality:5,punctuality:5,communication:5,comment:'Doublon interdit'},400)
await action({type:'role',role:'professionnel',proId:'1'})
let p=state.pros[0]
const dossier={type:'proProfile',name:p.name,bio:p.bio,zone:p.zone,zones:p.zones,categorie:p.categorie,experience:p.experience,phone:'',services:p.services,documents:{recto:[file],verso:[file],casier:[file]},submit:true}
await action(dossier);assert.equal(state.pros[0].kyc,'en_cours')
await action({type:'availability',available:true},400)
await action({type:'role',role:'client'})
await action({...input,requestKey:crypto.randomUUID()},400)
await action({type:'role',role:'administrateur'})
await action({type:'kyc',proId:'1',approve:false,reason:''},400)
await action({type:'kyc',proId:'1',approve:false,reason:'Pièces fictives à remplacer pour le scénario.'})
assert.equal(state.pros[0].kyc,'refuse')
await action({type:'role',role:'professionnel',proId:'1'})
await action(dossier)
await action({type:'role',role:'administrateur'})
await action({type:'kyc',proId:'1',approve:true,reason:'Pièces fictives examinées pour le test.'})
assert.equal(state.pros[0].kyc,'verifie')
await action({type:'settings',commission:7,autoHours:24})
await action({type:'adminServices',proId:'1',services:[{nom:'Service de test',tarif:10000}]})
await action({type:'role',role:'client'})
await action({...input,service:'Service de test',urgent:false,date:new Date(Date.now()+86400000).toISOString(),paymentMethod:'moov',requestKey:crypto.randomUUID()})
assert.equal(state.missions[0].totalPrice,10700)
await action({type:'transition',missionId:state.missions[0].id,action:'cancel'})
assert.equal(state.missions[0].payment,'sans_debit')
await action({type:'report',target:'Contact',reason:'Demande de test'})
await action({type:'read'})
assert(state.notifications.filter(n=>n.role==='client').every(n=>n.read))
await load();assert(state.missions.find(m=>m.id===missionId)?.review)
const other=await import('./auth-smoke.mjs?isolation')
const otherData=await (await other.sessionFetch('/api/workspace')).json()
assert(!otherData.state.missions.some(m=>m.id===missionId))
assert.equal((await other.sessionFetch('/api/files?id='+file.id)).status,404)
for(const route of ['/','/recherche','/professionnel/1','/login','/signup','/cgu','/confidentialite','/contact','/manifest.webmanifest','/service-worker-v1.js','/offline-v1.html']){
 response=await fetch(BASE+route);assert.equal(response.status,200,route)
}
for(const route of ['/accueil','/onboarding','/espace-pro','/espace-pro/dossier','/administration','/reserver/1','/reservations',`/reservations/${missionId}`,'/messages','/notifications','/favoris','/profil']){
 response=await sessionFetch(route);assert.equal(response.status,200,route)
}
console.log('PARCOURS API : PASS — réservation persistante, fichiers privés, KYC, messagerie, litige, validation, avis unique, commissions, annulation, notifications, isolation de comptes et routes.')
